src/edu/washington/escience/myria/util/HashUtils.java
test/edu/washington/escience/myria/operator/AggregateTest.java

Since we are mostly using 64-bit machines and according to the [doc](https://code.google.com/p/smhasher/wiki/MurmurHash3) this should give us better performance. I did a rough profiling and also have seen the improvement a little bit.

Use the hash function for x64

---

src/edu/washington/escience/myria/operator/RootOperator.java

If coalescing is enabled, the tuple batch returned by RootOperator may
have been incorrect because we returned the original, not coalesced,
batch.
Doubt this had much practical impact, but it could affect profiling results.

RootOperator: return the coalesced batch

---

.checkstyle-config

RedundantThrows has been removed from Checkstyle 6.2
http://checkstyle.sourceforge.net/releasenotes.html

Remove RedundantThrows from .checkstyle-config

---

src/edu/washington/escience/myria/MyriaConstants.java
src/edu/washington/escience/myria/api/LogResource.java
src/edu/washington/escience/myria/api/QueryResource.java
src/edu/washington/escience/myria/coordinator/catalog/MasterCatalog.java
src/edu/washington/escience/myria/operator/Operator.java
src/edu/washington/escience/myria/parallel/JsonSubQuery.java
src/edu/washington/escience/myria/parallel/Query.java
src/edu/washington/escience/myria/parallel/QueryManager.java
src/edu/washington/escience/myria/parallel/Server.java
src/edu/washington/escience/myria/parallel/SubQuery.java
src/edu/washington/escience/myria/profiling/ProfilingLogger.java
systemtest/edu/washington/escience/myria/systemtest/ServerTest.java

FYI @domoritz , I need this pretty bad for some of the work I'm doing and I'm thinking about how to get there.
A straw proposal that involves no frontend work is to simply add logging of events and physical plans for all subqueries and then add a subquery parameter to the frontend. I'm going to start there.

profiling of multi-subquery queries

---

.dictionary
src/edu/washington/escience/myria/coordinator/catalog/MasterCatalog.java
src/edu/washington/escience/myria/parallel/DatasetMetadataUpdater.java
src/edu/washington/escience/myria/parallel/Server.java

@domoritz identified a fairly slow transition between subqueries during yesterday's meeting. I took a guess that the issue is related to updating the catalog information about those subqueries on disk.
Here's some work that attempts to improve this behavior. Only loosely tested so far.

Query completion speedup

---

src/edu/washington/escience/myria/operator/LeapFrogJoin.java

Fix #689.
My belief is that the following happens: a fragment reaches EOS before
the entire query does. In this case, the root operator calls `cleanup()`
on its children, which leads to LFJ nulling out the `.tables` field.
However, the resource profiling code still measures the hash table
size, and thus was triggering an NPE.
@jingjingwang would appreciate your thoughts to see if this explanation makes any sense to you.

LeapFrogJoin: gracefully handle case when tables==null

---

src/edu/washington/escience/myria/api/MyriaExceptionMapper.java
src/edu/washington/escience/myria/api/encoding/IDBControllerEncoding.java
src/edu/washington/escience/myria/api/encoding/InMemoryOrderByEncoding.java
src/edu/washington/escience/myria/api/encoding/MyriaApiEncoding.java
src/edu/washington/escience/myria/api/encoding/QueryConstruct.java
src/edu/washington/escience/myria/api/encoding/SymmetricHashJoinEncoding.java
src/edu/washington/escience/myria/api/encoding/plan/DoWhileEncoding.java
src/edu/washington/escience/myria/api/encoding/plan/SequenceEncoding.java
src/edu/washington/escience/myria/api/encoding/plan/SubQueryEncoding.java
src/edu/washington/escience/myria/operator/BinaryOperator.java
src/edu/washington/escience/myria/operator/Operator.java
src/edu/washington/escience/myria/operator/RootOperator.java
src/edu/washington/escience/myria/operator/SymmetricHashJoin.java
src/edu/washington/escience/myria/operator/UnaryOperator.java

By default it's ALTER if not specified.
ALTER: pull both children alternatively.
LEFT: for each fetchNextReady(), start from the left child, and stick to pulling the left child until no data, then switch the the right child.
RIGHT: same as LEFT.

Jwang add join pull order encoding

---

src/edu/washington/escience/myria/storage/TupleBatch.java

Not sure if this was real or lurking from a debug scenario, but it's
expensive and redundant -- the storage engines down the line will do the
check.

TupleBatch: remove expensive check

---

.travis.yml

Don't cache the entire `$HOME/.gradle` directory, because it may
take time. Instead, follow this advice
http://forums.gradle.org/gradle/topics/travis-ci-caching-dependencies
and only cache the `.gradle/caches` directory.

travis-refine-cache

---

src/edu/washington/escience/myria/expression/ModuloExpression.java
test/edu/washington/escience/myria/operator/apply/ExpressionTest.java

Verifying that floating-point arguments for modulo operator fail typechecking. I didn't create any tests for mixed integral/floating-point types; should I?

Code/test changes to enable modulo operator.

---

src/edu/washington/escience/myria/io/UriSource.java

Since there is no registered Hadoop FileSystem for http/https schemes, explicitly check for these cases and use `java.net.URL` methods to retrieve an `InputStream`.
Corrects #721.

Support http and https schemes in UriSource

---

jsonQueries/nullChild_jortiz/ThreeWayLocalJoin.json
src/edu/washington/escience/myria/operator/BinaryOperator.java
src/edu/washington/escience/myria/operator/UnaryOperator.java
systemtest/edu/washington/escience/myria/systemtest/JsonQuerySubmitTest.java

During a fragment instantiation, the order of calls to operators' connect() can be arbitrary. getSchema() goes to generateSchema() which may need to know the children of an operator that may not have been set by connect(). On the other hand, I think it is unnecessary to call getSchema() in setChildren() since we can always generate schema after childrens are being set.

do not call getSchema() in setChildren()

---

src/edu/washington/escience/myria/operator/TipsyFileScan.java

When checking for the number of particles for star, dark and gas in the tipsy binary files, cosmo50 simulations would work just fine. Newer simulations (cosmo8) caused overflow issues during this check. Minor change was to cast the int multiplication/addition check to a long instead.

fix overflow bug with cosmo8

---

src/edu/washington/escience/myria/api/encoding/QueryConstruct.java
systemtest/edu/washington/escience/myria/systemtest/JsonOperatorTests.java

I think omitting all the FileScan operators from this list was an oversight; at any rate this is causing duplicate output whenever a query with a FileScan source is run on a cluster with more than one worker. Not sure if there are any potential gotchas; @mbalazin mentioned that one of the astronomy formats (Tipsy?) might have files with the same name on different workers with different contents, so I'd like to confirm if that is current usage.

Adding all *FileScan operators to list of singleton operators.

---

.gitignore

These are auto-generated files by the IntelliJ IDE that should not be stored in git repositories.

Add IntelliJ to .gitignore

---

src/edu/washington/escience/myria/coordinator/MasterCatalog.java

I had to make this fix on the fly during deployment because all sample queries from myria-web were succeeding but would not show results. The issue was a design oversight in the "delete relation" code: it always checked for the `is_deleted` flag to be set before deleting a relation from the catalog, but that only makes sense if we're going through the deletion API. In the overwrite scenario we shouldn't check the flag at all before deleting the relation.

Fixing deletion from catalog during overwrite.

---

build.gradle

if we ran two `./gradlew jar` without cleaning, it would fail to create the symlink because the link already exists.

fix jxm symlink overwrite.

---

src/edu/washington/escience/myria/api/encoding/QueryConstruct.java

The fragment may have been instantiated in a previous iteration with relations having different partitioning schemata that the current iteration caused by overwritting. Not cleaning up the assigned worker set gives us false conflicts.

clean assigned workers before instantiating.

---

src/edu/washington/escience/myria/api/MasterResource.java
src/edu/washington/escience/myria/util/DeploymentUtils.java
src/edu/washington/escience/myria/util/MyriaLauncher.java

Fixes #789 
Sample usage: `curl -i localhost:8753/server/restart`
I didn't add tests because this is just a stopgap measure until the `reef` branch is operational, but I have tested it manually.

add HTTP endpoint to restart cluster

---

src/edu/washington/escience/myria/parallel/LocalFragment.java
src/edu/washington/escience/myria/util/JVMUtils.java
src/edu/washington/escience/myria/util/concurrent/ErrorLoggingTimerTask.java
src/edu/washington/escience/myria/util/concurrent/ExecutableExecutionFuture.java
src/edu/washington/escience/myria/util/concurrent/OperationFutureBase.java
src/edu/washington/escience/myria/util/concurrent/RenamingThreadFactory.java

When the JVM is close to an OOM state, the OOM error can be thrown at any time by any thread, even threads that are not used for query processing. The old implementation takes a long way to propagate an OOM error from the lowest level to Worker level, and the system state can crash during this process so that the query is still marked as running but the JVM cannot respond anymore. On the other hand, it is unnecessary to clean up after an OOM since the JVM is in an OOM state anyway. So we terminate the worker process when an OOM is detected.

make JVM exit when OOM

---

build.gradle

otherwise we have both 1.9 and 2.14 jersey-server and cluster can't launch.

exclude old jersey-server from our repo

---

src/edu/washington/escience/myria/operator/BinaryFileScan.java
src/edu/washington/escience/myria/operator/FileScan.java
test/edu/washington/escience/myria/operator/BinaryFileScanTest.java

This enables support for binary ingest of data with schema containing BOOLEAN or STRING types. The String encoding is variable-width; it reads the length of the string, then the string itself, as expected from `DataOutputStream.readUTF()`.

Binary ingest support for Booleans and Strings

---

src/edu/washington/escience/myria/TupleWriter.java
src/edu/washington/escience/myria/api/encoding/DataOutputEncoding.java
src/edu/washington/escience/myria/api/encoding/OperatorEncoding.java
src/edu/washington/escience/myria/io/DataSink.java

Currently, there's no way to encode the DataOutput operator. We were also missing JSON subtype annotation for UriSink and for the different types of supported TupleWriters.

encoding for DataOutput operator

---

src/edu/washington/escience/myria/operator/CSVFileScanFragment.java

@parmitam  was our first tester and ran into a bug. I realized I forgot to test the last changes we made for more than 2 workers. 
With this fix, I tested for 3 and 5 workers by temporarily adding workers to the SystemTestBase class.
Two fixes:
1) I added a global variable ```byteOffsetFromTruncatedRowAtStart``` which keeps track of the number of bytes we read when skipping over the first partial row. This variable becomes important in cases when a worker needs to reinitialize the parser -- we must have the correct offset otherwise our character skipping will be incorrect. Our 2-worker tests did not cover this because worker 1 never has to worry about this offset when reinitializing the parser (it is always going to be 0) and worker 2 is the last worker so it doesn't need to reinitialize …

parallel ingest bug fix

---

src/edu/washington/escience/myria/daemon/MyriaDriverLauncher.java

In order for the DriverLauncher to work, it must have a directory that is writeable by the DriverLauncher and readable by the launched Driver, on whatever node that Yarn allocates the Driver to.  The DriverLauncher places the myria jar and other configuration information inside this location, for transfer to the Driver itself.
The default file system this directory exists in is given by the fs.defaultFS parameter in core-site.xml.  If the defaultFS parameter is not specified, it defaults to file:///.  If you need to change the filesystem (say, to HDFS or to S3). then modify core-site.xml.
The default file location within the filesystem is /tmp.  If you need to change this, then specify the -driverDir parameter on the command line when you start Myria.
*** This will allow you to use Myria …

driverDir CLI; revamp CLI usage printing

---

src/edu/washington/escience/myria/io/UriSource.java

This fixes exceptions like this which are filling the logs with noise:
```
17/01/25 19:56:49 WARN coordinator.MasterCatalog: Error deserializing plan for query #5
com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class edu.washington.escience.myria.io.UriSource] value failed: Parameter uri to UriSource may not be null (through reference chain: java.util.ArrayList[1]->edu.washington.escience.myria.api.encoding.PlanFragmentEncoding["operators"]->java.util.ArrayList[0]->edu.washington.escience.myria.api.encoding.TupleSourceEncoding["source"])
at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:405)
at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.jav …
```

add URI string accessor

---

src/edu/washington/escience/myria/io/AmazonS3Source.java

This is mostly for the local deployment case. If no property name is found, we should use AnonymousAWSCredentialsProvider.

adding anonymous credentials as default

---

myriadeploy/launch_local_cluster

After setting `set -e` in #886, `cp -n` would cause the script to exit if `deployment.cfg` were already there. According to https://www.freebsd.org/cgi/man.cgi?cp, `-n` is non-standard so use an `if` to detect that.

cp -n return non-zero code when deployment.cfg exists

---

src/edu/washington/escience/myria/CsvTupleReader.java
src/edu/washington/escience/myria/api/encoding/CSVFragmentTupleSourceEncoding.java
src/edu/washington/escience/myria/api/encoding/OperatorEncoding.java
src/edu/washington/escience/myria/operator/CSVFragmentTupleSource.java
src/edu/washington/escience/myria/parallel/Server.java

Fixed the encoding so we use the CSV parameters from the CsvTupleReader. Also, renamed `CSVFileScanFragment` to `CSVFragmentTupleSource` to match with `TupleSource`.

Fixed the encoding for CSVFragmentTupleSource

---

src/edu/washington/escience/myria/operator/CSVFragmentTupleSource.java

Fixing an ingest bug for cases where parallel ingest only needed a single worker to read a file. With the old code, every worker would try to read the entire file (since `workerIndex` value was kept at 0). In other words, every worker would believe they were the first worker. 
Now, `workerIndex` starts at -1 and is only assigned to read the file if it is found in the workerIds array. If `workerIndex` is kept at -1, we mark `flagAsIncomplete` as True which then makes sure to not initialize the parser for the current worker.

fixing parallel ingest single worker case

---

src/edu/washington/escience/myria/MyriaConstants.java
src/edu/washington/escience/myria/column/builder/BlobColumnBuilder.java
src/edu/washington/escience/myria/column/builder/BooleanColumnBuilder.java
src/edu/washington/escience/myria/column/builder/ColumnBuilder.java
src/edu/washington/escience/myria/column/builder/ColumnFactory.java
src/edu/washington/escience/myria/column/builder/DateTimeColumnBuilder.java
src/edu/washington/escience/myria/column/builder/DoubleColumnBuilder.java
src/edu/washington/escience/myria/column/builder/FloatColumnBuilder.java
src/edu/washington/escience/myria/column/builder/IntColumnBuilder.java
src/edu/washington/escience/myria/column/builder/LongColumnBuilder.java
src/edu/washington/escience/myria/column/builder/StringColumnBuilder.java
src/edu/washington/escience/myria/expression/evaluate/GenericEvaluator.java
src/edu/washington/escience/myria/expression/evaluate/PythonUDFEvaluator.java
src/edu/washington/escience/myria/operator/Counter.java
src/edu/washington/escience/myria/operator/SampledDbInsertTemp.java
src/edu/washington/escience/myria/operator/StatefulApply.java
src/edu/washington/escience/myria/storage/TupleUtils.java
test/edu/washington/escience/myria/column/BlobColumnTest.java
test/edu/washington/escience/myria/column/BooleanColumnTest.java
test/edu/washington/escience/myria/column/DateTimeColumnTest.java
test/edu/washington/escience/myria/column/DoubleColumnTest.java
test/edu/washington/escience/myria/column/FloatColumnTest.java
test/edu/washington/escience/myria/column/IntColumnTest.java
test/edu/washington/escience/myria/column/LongColumnTest.java
test/edu/washington/escience/myria/column/StringColumnTest.java
test/edu/washington/escience/myria/operator/AggregateTest.java
test/edu/washington/escience/myria/operator/StreamingAggTest.java
test/edu/washington/escience/myria/operator/apply/ApplyTest.java

By default, a column builder reserves 10k data except `BlobColumnBuilder`. However, when a list of columns (including a blob column) is allocated, the blob column is of size 1 while other columns are of size 10k. This caused OOM when we modified `ApplyTest.testApply()` by adding a blob column to its schema -- since each `TupleBatch` is now of size 1, the test created 20k `TupleBatch`es, each has a few columns of size 10k (and one blob column of size 1). 
Fix this bug by passing the size to a column builder, instead of getting its size based on its type internally.

specify a size to a column builder
