uwescience/myria

myriadeploy/update_myria_binaries.py
I also renamed the script name as suggested in #665 but open to other good names.
=> Also sync sqlite4java

myriadeploy/deployment.cfg.postgres, myriadeploy/myriadeploy.py, speedtest/edu/washington/escience/myria/accessmethod/BenchmarkTest.java, src/edu/washington/escience/myria/MyriaConstants.java, src/edu/washington/escience/myria/accessmethod/ConnectionInfo.java, src/edu/washington/escience/myria/coordinator/catalog/CatalogMaker.java, src/edu/washington/escience/myria/parallel/MasterSubQuery.java
Update to last pull request with fix for failing test and changes based on suggestions.
=> lbrendanl postgres config

src/edu/washington/escience/myria/accessmethod/JdbcAccessMethod.java
Speeds up `scan`->`sink` query plans by ~10%. Not a huge improvement, but worth it to me!
See https://github.com/pgjdbc/pgjdbc/commit/dbf76c2d662896c5703cf20d7362e1d061e1e43f#diff-0ae7d0b506fb16e9c9418a3e10ae7981R16
=> postgres jdbc: use binary transfer on read

src/edu/washington/escience/myria/parallel/QueryManager.java
=> QueryManager: fix method of detecting whether a query is finished

src/edu/washington/escience/myria/profiling/ProfilingLogger.java
From 20s of seconds for a few-minutes query to under 1s.
=> Sending relation: create the index we need

src/edu/washington/escience/myria/parallel/LocalFragment.java, src/edu/washington/escience/myria/parallel/TransportMessageSerializer.java, src/edu/washington/escience/myria/parallel/ipc/IPCMessageHandler.java, src/edu/washington/escience/myria/parallel/ipc/StreamInputChannel.java
Several IPC fixes discovered during my experiments.
=> Fix ipc channel failure

src/edu/washington/escience/myria/coordinator/catalog/MasterCatalog.java, test/edu/washington/escience/myria/coordinator/catalog/CatalogTest.java
Related to ongoing work for uwescience/myria-web#265
=> MasterCatalog: populate language in querySimpleStatusHelper

myriadeploy/relaunch_updated_myria.sh
=> fix for relaunching script

src/edu/washington/escience/myria/storage/TupleBatch.java
Error message confused me when I first ran into it.
=> better error message for TupleBatch constructor

myriadeploy/create_deployment.py
I need a command-line utility to generate deployment files for EC2- and HPC-oriented deployments.  Since this seems broadly useful, I thought we might include it in the distribution.
=> Utility to create deployment files from the command line

src/edu/washington/escience/myria/operator/Limit.java, src/edu/washington/escience/myria/operator/agg/StreamingAggregate.java, test/edu/washington/escience/myria/operator/LimitTest.java, test/edu/washington/escience/myria/operator/StreamingAggTest.java
adding streaming aggregate class and test, modified Limit.java to stop ingesting tuples from child when reached limit
=> adding streaming aggregate & limit operator

build.gradle, conf/jmxetric.xml, myriadeploy/deployment.cfg.postgres, myriadeploy/deployment.cfg.sample, src/edu/washington/escience/myria/MyriaSystemConfigKeys.java, src/edu/washington/escience/myria/util/DeploymentUtils.java
Currently in production, so you can go to http://dbserver20.cs.washington.edu/ganglia/ and take a look :)
=> JVM metrics for Ganglia

src/edu/washington/escience/myria/api/encoding/DbInsertEncoding.java, src/edu/washington/escience/myria/api/encoding/TempInsertEncoding.java, src/edu/washington/escience/myria/coordinator/MasterCatalog.java, src/edu/washington/escience/myria/operator/DbInsert.java, src/edu/washington/escience/myria/operator/DbInsertTemp.java, src/edu/washington/escience/myria/parallel/RelationWriteMetadata.java
Fixes #766
https://github.com/uwescience/raco/pull/450 must be merged before this can be merged.
=> write partitioning metadata when storing relation

src/edu/washington/escience/myria/util/DeploymentUtils.java
Fixes https://github.com/uwescience/myria/issues/781.
=> always create a clean catalog when there is no existing one

.travis.yml, travis/before_install.sh
We can eliminate this trivial test when we add a real test for S3 export.
=> add IAM user to travis with temp S3 test

src/edu/washington/escience/myria/operator/TipsyFileScan.java
There are several classes that all contain their own "load from x" functionality; this should be centralized at some point.
=> Add support for loading Tipsy data from HDFS

src/edu/washington/escience/myria/api/DatasetResource.java, src/edu/washington/escience/myria/parallel/Server.java
If for any reason we cannot get the dataset status due to a failed ingestion, return a proper error message.
=> check null in doIngest.

src/edu/washington/escience/myria/io/DataSink.java, src/edu/washington/escience/myria/io/FileSink.java, test/edu/washington/escience/myria/operator/DataSinkTest.java
Sink for pushing directly to the file system, and an integration test that verifies that the export is successfully written.
=> Support sinking to local file system

src/edu/washington/escience/myria/expression/ExpressionOperator.java, src/edu/washington/escience/myria/expression/NgramExpression.java, src/edu/washington/escience/myria/expression/SequenceExpression.java, test/edu/washington/escience/myria/operator/apply/ApplyNgramTest.java, test/edu/washington/escience/myria/operator/apply/ApplySequenceTest.java, test/edu/washington/escience/myria/operator/apply/FlatteningApplyTest.java
The main contribution in this PR is `NgramExpression` (which I'll be adding support for to https://github.com/uwescience/raco/pull/537).
=> Flatmap expressions

src/edu/washington/escience/myria/api/DatasetResource.java, src/edu/washington/escience/myria/parallel/Server.java
Solves #730. Will add an integrated test once this feature is in Python.
=> add limit to the dataset download api
